services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Laad de omgevingsvariabelen uit het .env bestand
    # Dit is nodig voor de Supabase URL en Anon Key
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      # De URL van de backend API, zodat de frontend weet waar de API te vinden is.
      - REACT_APP_API_URL=http://localhost:3001/api

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Laad de omgevingsvariabelen uit het .env bestand
    # Dit bevat nu de Supabase keys en de DATABASE_URL naar Supabase
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"

# De lokale postgres database is niet meer nodig, we gebruiken Supabase.
# Het 'volumes' blok kan nu volledig verwijderd worden als er geen andere volumes zijn.
# Voor dit project is het 'postgres-data' volume niet meer relevant.
