services:
  frontend:
    build: ./frontend
    ports:
      # Map host-poort 3000 naar container-poort 3000 voor de frontend
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # Verwijder de volgende regel om te voorkomen dat lokale node_modules
      # de geïnstalleerde modules in de container overschrijven.
      # - /app/node_modules 
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      # De URL van de backend API, zodat de frontend weet waar de API te vinden is.
      # Gebruik de servicenaam 'backend' binnen het Docker-netwerk
      - REACT_APP_API_URL=http://backend:3001/api

  backend:
    build: ./backend
    ports:
      # Map host-poort 3001 naar container-poort 3001 voor de backend
      - "3001:3001"
    volumes:
      - ./backend:/app
      # Verwijder de volgende regel om te voorkomen dat lokale node_modules
      # de geïnstalleerde modules in de container overschrijven.
      # - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    # Gebruik 'npm run dev' voor de backend, zoals oorspronkelijk bedoeld voor hot-reloading
    command: npm run dev
