services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # De URL van de backend API, zodat de frontend weet waar de API te vinden is.
      - REACT_APP_API_URL=http://localhost:3001/api

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Laad de omgevingsvariabelen uit het .env bestand
    env_file:
      - .env
    environment:
      # Overschrijf DB_HOST om de interne servicenaam van Docker te gebruiken
      - DB_HOST=db
      - NODE_ENV=development
    depends_on:
      - db # Zorgt ervoor dat de database start vóór de backend

  db:
    image: postgres:15-alpine
    restart: always
    # Laad de database credentials uit het .env bestand
    env_file:
      - .env
    ports:
      # Maakt de database poort beschikbaar op je computer voor tools zoals DBeaver
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Zorgt dat data bewaard blijft

volumes:
  postgres-data: # Definieert het volume voor data persistentie
